name: ci

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  #
  # A basic and simple test run to gate the heavier matrix below.
  #
  simple-test:
    name: "Simple TestRun"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 0
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 0

    steps:
      - uses: actions/checkout@v6
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        uses: perl-actions/install-with-cpm@v2
        with:
          sudo: true
          global: true
          cpanfile: "cpanfile"
      - name: Makefile.PL
        run: perl Makefile.PL
      - name: make test
        run: make test

  perl-versions:
    needs: [simple-test]
    runs-on: ubuntu-latest
    name: List Perl versions
    outputs:
      perl-versions: ${{ steps.action.outputs.perl-versions }}
    steps:
      - id: action
        uses: perl-actions/perl-versions@v2.0
        with:
          since-perl: '5.24'
          with-devel: true

  linux:
    name: "Perl ${{ matrix.perl-version }}"
    needs: [simple-test, perl-versions]
    runs-on: ubuntu-latest

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    strategy:
      fail-fast: false
      matrix:
        perl-version: ${{ fromJson(needs.perl-versions.outputs.perl-versions) }}

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v6
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        uses: perl-actions/install-with-cpm@v2
        with:
          sudo: false
          global: false
          cpanfile: "cpanfile"
      - name: Set PERL5LIB to local lib
        run: echo "PERL5LIB=$(pwd)/local/lib/perl5" >> $GITHUB_ENV
      - name: Makefile.PL
        run: perl Makefile.PL
      - name: make test
        run: make test

  macos:
    name: macOS
    needs: [simple-test]
    runs-on: macos-latest

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    steps:
      - uses: actions/checkout@v6
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        uses: perl-actions/install-with-cpm@v2
        with:
          sudo: true
          global: true
          cpanfile: "cpanfile"
      - name: Makefile.PL
        run: perl Makefile.PL
      - name: make test
        run: make test

  windows:
    name: Windows
    needs: [simple-test]
    runs-on: windows-latest

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTOMATED_TESTING: 1

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v6
      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpanm --installdeps --cpanfile cpanfile --with-develop --notest .
      - name: Makefile.PL
        run: perl Makefile.PL
      - name: gmake
        run: gmake
      - name: gmake test
        run: gmake test

  author-tests:
    name: "Author tests"
    needs: [simple-test]
    runs-on: ubuntu-latest

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    container:
      image: perldocker/perl-tester:latest

    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        uses: perl-actions/install-with-cpm@v2
        with:
          sudo: false
          global: false
          cpanfile: "cpanfile"
      - name: Set PERL5LIB to local lib
        run: echo "PERL5LIB=$(pwd)/local/lib/perl5" >> $GITHUB_ENV
      - name: Makefile.PL
        run: perl Makefile.PL
      - name: Run author tests
        run: prove -l xt/*.t

  cpan-install:
    name: "CPAN install simulation (no .git)"
    needs: [simple-test]
    runs-on: ubuntu-latest

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTOMATED_TESTING: 1
      SMOKE_INSTDIR: ./TS

    container:
      image: perldocker/perl-tester:latest

    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        uses: perl-actions/install-with-cpm@v2
        with:
          sudo: false
          global: false
          cpanfile: "cpanfile"
      - name: Set PERL5LIB to local lib
        run: echo "PERL5LIB=$(pwd)/local/lib/perl5" >> $GITHUB_ENV
      - name: Makefile.PL
        run: perl Makefile.PL
      - name: Remove .git directory to simulate a download from CPAN (or GitHub)
        run: rm -rf .git
      - name: make test
        run: make test
